### ISSUE TITLE
Self-tests that are not working : map_ojp_to_nova

### ISSUE THREAD

**Issue by ue71603** [openTdataCH/ojp-nova#17]
### map_ojp_to_nova has an error when run as main.
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 36, column 99

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/development/github/ojp-nova/map_ojp_to_nova.py", line 140, in <module>
    ojp = parser.parse('generated/ojp_fare_request.xml', Ojp)
  File "D:\development\2023-04_ojpfare2nova\ojp-nova-master\venv\lib\site-packages\xsdata\formats\dataclass\parsers\bases.py", line 56, in parse
    raise ParserError(e)
xsdata.exceptions.ParserError: not well-formed (invalid token): line 36, column 99

**Comment by skinkie** [comment]
@ue71603 this is not from the master branch.

**Comment by ue71603** [comment]
@skinkie  no this is from https://github.com/openTdataCH/ojp-nova/pull/11   but I think I didn't change things in the XMLs
